name: cw-depth-server
'on':
  push:
    # - branch: release
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deployment:
    name: 'self-hosted'
    runs-on: self-hosted
    steps:
      - name: Pull
        working-directory: /home/ubuntu/AdelaiDepth
        run: git pull
      # - name: Activate venv
      #   run: conda activate adelai
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      # - name: Lint
      #   run: TODO | required ??
      - name: Activate venv and start server
        run: source run.sh
